---
development:
  cloud_name: katherina
  api_key: '877138951421819'
  api_secret: UYadIB3fHZFDZCCeE7f1XmBJN-s
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: katherina
  api_key: '877138951421819'
  api_secret: UYadIB3fHZFDZCCeE7f1XmBJN-s
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: katherina
  api_key: '877138951421819'
  api_secret: UYadIB3fHZFDZCCeE7f1XmBJN-s
  enhance_image_tag: true
  static_image_support: false
